AnyLocalizedError: properly support NSError inputs (#85)
# AnyLocalizedError: properly support NSError inputs

## :recycle: Current situation & Problem
`NSError` doesn't conform to `LocalizedError`, but does typically carry
information that can be used to populate the interface defined by
`LocalizedError`.
the current logic in the `AnyLocalizedError` initializer only checks for
`LocalizedError` conformances, and ends up missing `NSError`, instead
ending up in the `error is CustomStringConvertible` branch, which only
retrieves the error's description.

this PR fixes this, by properly detecting `NSError`s, and populating the
`AnyLocalizedError`'s properties from the `NSError` instead of only
using the (much less useful) description.


## :gear: Release Notes
- `AnyLocalizedError` now has better handling for `NSError` errors


## :books: Documentation
n/a


## :white_check_mark: Testing
yes!!!


## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our
[Code of
Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md)
and [Contributing
Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of
Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md)
and [Contributing
Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).